#!/usr/bin/bash




_togglemute(){
    for id in $(pactl list short sinks | awk '{print$1}'); do
       pactl set-sink-mute $id toggle
    done;
}

_switchport(){
	active_ch=$(pacmd list-sinks  |awk '/\* index/{print$3}')  # ------------v------ to remove tabs as tabs dont get rendered in dmenu
 	name=$(pacmd list-sinks | grep -v active |awk -F ':' '/-output-/{print$1}' | awk '{print$1}' |dmenu -p "Select Audio Port [name]" -i -l 4 | awk '/[a-zA-Z0-9\-]/{print$1}');
    for id in $(pactl list short sinks | awk '{print$1}'); do
        pactl set-sink-port $id $name
    done;
}

_switchch(){
	check=$(pactl list short sinks|grep mono_audio)
	if [ -z "$check" ]; then
        master="master=$(pacmd info  | awk '/sink:/{print$3}' | tr -d '<>')"
        echo $master
		pacmd load-module module-remap-sink sink_name=mono_audio master=alsa_output.pci-0000_00_1f.3.analog-stereo channels=1 channel_map=mono
	fi
	pactl list short sinks | awk '{print$2"    "$4"    "$5}'|dmenu -p "Select Audio Channel [name|bitrate|channel]" -i -l 4 |awk '{print$1}'|xargs -I{} pactl set-default-sink {}
}

case $1 in
	"p" )_switchport;;
	"c") _switchch;;
	"m") _togglemute;;
esac
