#!/usr/bin/bash

function volume() {

    pactl set-sink-volume @DEFAULT_SINK@ $1
    volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F'/' '/Volume/ {gsub(/ /,""); print $2;}')
    dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "$HOME/Pictures/icons/sound.png" "Volume: ${volume}%" -t 2000 &
}

function brightness() {
    brigt=$(cat /sys/class/backlight/intel_backlight/brightness)
    brigt=$(($brigt+$1))
    echo "$brigt" | tee /sys/class/backlight/intel_backlight/brightness &>/dev/null || brigt=$(($brigt-$1))
    dunstify -a "changebrightness" -u low -r "9992" -h double:value:$brigt -i "$HOME/Pictures/icons/brightness.png" "Brightness:$(($brigt*100/7500))%" -t 2000 &
}

case $1 in
    "vup" ) volume +2%
        ;;
    "vdown" ) volume -2%
        ;;
    "bup" )  brightness 100
        ;;
    "bdown" )  brightness -100
        ;;
esac
