#! /usr/bin/bash


year=$(date +%Y)
month=$(date +%m)
day=$(date +%d)

list_file(){
    cd "$1" &&
    for file in $(ls); do
      echo "file '$PWD/$file'" >> "/home/tester/Videos/TimeLapse/$year/$month/$day/list.txt"
    done
    echo "Done Listing.. this folder...$1"
}

_book_mark(){
    book_mark_path="/home/tester/.config/gtk-3.0"
    total=$(cat "$book_mark_path/bookmarks"| wc -l)
    total=$(bc <<< "$total-1")
    cat "$book_mark_path/bookmarks"  | head "-$total" | tee "$book_mark_path/bookmarks"
    echo "file:///home/tester/Videos/TimeLapse/$year/$month/$day" | tee -a "$book_mark_path/bookmarks"
}
compile(){
    ffmpeg -safe 0 -f concat -i "/home/tester/Videos/TimeLapse/$year/$month/$day/list.txt"  -c:v libx264  -preset fast -threads 4 "/home/tester/Videos/TimeLapse/$year/$month/$day/output.mp4" && _book_mark 
}

__test(){
    base_dir="/home/tester/Pictures/TimeLapse"
    mkdir -p "/home/tester/Videos/TimeLapse/$year/$month/$day/"
    today_now="$(date +'%Y/%m/%d')"
    dir2="$base_dir/$year/$month/$day"
    list_file "$dir2"
}

_ready(){
    base_dir="/home/tester/Pictures/TimeLapse"
    mkdir -p "/home/tester/Videos/TimeLapse/$year/$month/$day/"
    today_now="$(date +'%Y/%m/%d')"
    yesterday=`date --date=$today_now'-1 day' +'%Y/%m/%d'`
    dir="$base_dir/$yesterday"
    if [ -d "$dir" ]; then
        mv "$dir" "$dir.used" && list_file "$dir.used"
    fi
    dir2="$base_dir/$year/$month/$day"
    mv "$dir2" "$dir2.done" && list_file "$dir2.done"
    compile
}
_ready
# __test
# _book_mark
