#! /usr/bin/bash


year=$(date +%Y)
month=$(date +%m)
day=$(date +%d)


function final(){
    vids="/home/tester/Videos/TimeLapse/$year/$month/$day/vids.txt"
    ffmpeg -safe 0 -f concat -i "$vids" -c:v libx264 -preset fast -pix_fmt yuv420p "/home/tester/Videos/TimeLapse/$year/$month/$day/output.mp4" \
    >> "/home/tester/Videos/TimeLapse/$year/$month/$day/final_compile.log" || echo "[Final] There Was Some Error Check Log File"

}

function compile(){
    output=""
    if [[ $1 == *".used" ]]; then
        output="resedue.mp4"
    else
        output="todaycompile.mp4"
        echo "file '/home/tester/Videos/random/spong_bob_the_next_day.mp4' " >> "/home/tester/Videos/TimeLapse/$year/$month/$day/vids.txt"
    fi
    ffmpeg -framerate 30 -pattern_type glob -i "$1/*.jpg" -c:v libx264 -preset fast -threads 4 -f mp4 "/home/tester/Videos/TimeLapse/$year/$month/$day/$output" \
    >> "/home/tester/Videos/TimeLapse/$year/$month/$day/compile.log" || echo "[Head] ($output) There Was Some Error Check Log File"
    echo "file '/home/tester/Videos/TimeLapse/$year/$month/$day/$output'" >> "/home/tester/Videos/TimeLapse/$year/$month/$day/vids.txt"

}
function _ready(){
    base_dir="/home/tester/Pictures/TimeLapse"
    mkdir -p "/home/tester/Videos/TimeLapse/$year/$month/$day/"
    dir="$base_dir/$year/$month/$((day - 1))"
    if [ -d "$dir" ]; then
        mv "$dir" "$dir.used"
        compile "$dir.used"
    fi
    dir="$base_dir/$year/$month/$day"
    mv "$dir" "$dir.done"
    compile "$dir.done"
    final
}


_ready