#!/bin/bash

function send_notification() {
    volume=$(amixer sget Master | grep -oP '\d+(?=%)')
    dunst -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "~/Pictures/icons/sound.png" "Volume: ${volume}%" -t 2000
}

send_notification
